### ISSUE TITLE
Getting an error when updating the project

### ISSUE THREAD

**Issue by piyumiperera** [VTAF/VirtusaSeleniumWebdriverRuntime#2]
I am getting below error when updating the maven project.

"cannot nest 'seleniumwebdriver/src/main/resources' inside 'seleniumwebdriver/src'/ To enable the nesting exclude 'main/' from 'seleniumwebdriver/src' "

**Comment by debugger89** [comment]
Fixed with the commit ec0b606d8160904b72d4cc755e9b907c31258211
